apiVersion: v1
kind: Service
metadata:
  name: weather-app-uat
  namespace: demo-env-uat
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32001
      protocol: TCP
  type: NodePort
  selector:
    app: weather-app
